#!/bin/bash
function get(){
  curl -L "https://plutoniumm.github.io/htmx/$1.txt" > "$1.txt";
};

function unseal(){
  # extract dir from txt file
  file="$1"
  if [ -z "$file" ]; then
    echo "Usage: unseal <file>";
    return 1;
  fi
  if [ ! -f "$file" ]; then
    echo "Error: $file is not a file";
    return 1;
  fi

  echo "Unsealing $file";
  rm -rf "$dir";

  path=""
  while IFS= read -r line; do
    if [ "${line:0:4}" == "#-# " ]; then
      path="${line:4}";
      echo "Creating ./$path";
      mkdir -p "$(dirname "./$path")";
    else
      # if path is empty, we're not in a file
      if [ -z "$path" ]; then
        continue;
      fi
      echo -e "$line" >> "./$path";
    fi
  done < "$file";

  rm "$file";
};

languages=( "go-templ" "ocaml-dream" "ts-bun" "haskell-yesod" "ruby-rails"
"c-none" "lua-pegasus" "php-none" "rust-leptos" "python-jinja" );
function ask(){
  echo "Which language do you want to use?";

  select lang in "${languages[@]}"; do
    if [ -n "$lang" ]; then
      echo "You chose $lang";
      get "$lang";
      break;
    else
      echo "Invalid choice";
    fi
  done

  echo "Enter name of directory (.)";
  read dir;
  if [ -z "$dir" ]; then
    dir=".";
  fi

  if [ "$dir" != "." ]; then
    mkdir -p "$dir";
    mv "$lang.txt" "$dir";
    cd "$dir";
  fi

  unseal "$lang.txt";
};

ask;