name:    haskell-yesod
version: "0.0.0"

dependencies:

- base >=4.9.1.0 && <5
- yesod >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-static >=1.6 && <1.7
- classy-prelude >=1.5 && <1.6
- classy-prelude-yesod >=1.5 && <1.6
- text >=0.11 && <2.0
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- warp >=3.0 && <3.4

library:
  source-dirs: src

# Runnable executable for our application
executables:
  haskell-yesod:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-yesod